***
# <font color=green size=10>ANÁLISE DE DADOS DO CENSO 2015</font>
***  

>## 😃 **FAÇA A SUA CÓPIA NO DRIVE 👉ANTES👈 DE PREENCHER E EXECUTAR AS CÉLULAS DE CÓDIGO!**
Renomeie este arquivo como **Distribuicao_de_Frequencias_02062026.ipynb**, copie/cole o novo nome em cima do atual (ao lado do ícone do Drive).

# <font color=green>1 CONHECENDO OS DADOS</font>
***

## <font color=green>1.1 Dataset do projeto</font>
***

### Pesquisa Nacional por Amostra de Domicílios - 2015

<p align=justify> A <b>Pesquisa Nacional por Amostra de Domicílios - PNAD</b> investiga anualmente, de forma permanente, características gerais da população, de educação, trabalho, rendimento e habitação e outras, com periodicidade variável, de acordo com as necessidades de informação para o país, como as características sobre migração, fecundidade, nupcialidade, saúde, segurança alimentar, entre outros temas. O levantamento dessas estatísticas constitui, ao longo dos 49 anos de realização da pesquisa, um importante instrumento para formulação, validação e avaliação de políticas orientadas para o desenvolvimento socioeconômico e a melhoria das condições de vida no Brasil.</p>

### Fonte dos Dados

https://ww2.ibge.gov.br/home/estatistica/populacao/trabalhoerendimento/pnad2015/microdados.shtm

### Variáveis utilizadas

> ### Renda
> ***

Rendimento mensal do trabalho principal para pessoas de 10 anos ou mais de idade.

> ### Idade
> ***

Idade do morador na data de referência em anos.

> ### Altura (elaboração própria)
> ***

Altura do morador em metros.

> ### UF
> ***

|Código|Descrição|
|---|---|
|11|Rondônia|
|12|Acre|
|13|Amazonas|
|14|Roraima|
|15|Pará|
|16|Amapá|
|17|Tocantins|
|21|Maranhão|
|22|Piauí|
|23|Ceará|
|24|Rio Grande do Norte|
|25|Paraíba|
|26|Pernambuco|
|27|Alagoas|
|28|Sergipe|
|29|Bahia|
|31|Minas Gerais|
|32|Espírito Santo|
|33|Rio de Janeiro|
|35|São Paulo|
|41|Paraná|
|42|Santa Catarina|
|43|Rio Grande do Sul|
|50|Mato Grosso do Sul|
|51|Mato Grosso|
|52|Goiás|
|53|Distrito Federal|

> ### Sexo
> ***

|Código|Descrição|
|---|---|
|0|Masculino|
|1|Feminino|

> ### Anos de Estudo
> ***

|Código|Descrição|
|---|---|
|1|Sem instrução e menos de 1 ano|
|2|1 ano|
|3|2 anos|
|4|3 anos|
|5|4 anos|
|6|5 anos|
|7|6 anos|
|8|7 anos|
|9|8 anos|
|10|9 anos|
|11|10 anos|
|12|11 anos|
|13|12 anos|
|14|13 anos|
|15|14 anos|
|16|15 anos ou mais|
|17|Não determinados|
||Não aplicável|

> ### Cor
> ***

|Código|Descrição|
|---|---|
|0|Indígena|
|2|Branca|
|4|Preta|
|6|Amarela|
|8|Parda|
|9|Sem declaração|

#### <font color='red'>Observação</font>
***
> Os seguintes tratamentos foram realizados nos dados originais:
> 1. Foram eliminados os registros onde a <b>Renda</b> era inválida (999 999 999 999);
> 2. Foram eliminados os registros onde a <b>Renda</b> era missing;
> 3. Foram considerados somente os registros das <b>Pessoas de Referência</b> de cada domicílio (responsável pelo domicílio).

## 📌 SE NECESSÁRIO, **COMPLETE** O CÓDIGO MARCADO COM **???** E **EXECUTE** CADA CÉLULA COM O BOTÃO ▶

### Importando pandas e lendo o dataset do projeto

https://pandas.pydata.org/

In [3]:
# EXECUTE!
# Importa bibliotecas necessarias ao projeto - reunir todo os comandos import no início do notebook
# bibliotecas ndas, numpy, seaborn, spicy
import pandas as pd # complete os códigos, onde tem o sinal "?"
import numpy as np
import seaborn as sns
import spicy as sp

In [4]:
# SE HOUVER O ERRO "ModuleNotFoundError: No module named 'spicy'", DEPOIS DE IMPORTAR BIBLIOTECAS,
# EXECUTE ESTA CÉLULA UMA ÚNICA VEZ para instalar 'spicy' e execute de novo a célula anterior de import

!pip install spicy #Remova o # inicial para executar e reponha depois de executada (assim evita repetir sem necessidade)

Requirement already satisfied: spicy in /usr/local/lib/python3.12/dist-packages (0.16.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from spicy) (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy->spicy) (2.0.2)

In [5]:
# Mostra versoes das bibliotecas importadas
print('Versão do pandas -> %s' % pd.__version__)
print('Versão do numpy -> %s' % np.__version__)
print('Versão do seaborn -> %s' % sns.__version__)
print('Versão do scipy -> %s' % sp.__version__)

Versão do pandas -> 2.2.2
Versão do numpy -> 2.0.2
Versão do seaborn -> 0.13.2
Versão do scipy -> 1.16.3

_Upload dos dados_: clique no ícone de pasta no lado esquerdo e na folha com seta, selecione o arquivo "dados.csv" em pasta no computador (possivelmente Downloads). Será exibida mensagem sobre exclusão dos arquivos ao fechar o ambiente de execução, clique em OK e aguarde concluir o upload.

In [6]:
# EXECUTE!
# Carregamento do dataset dados.csv - clique no play para começar ou recomeçar
dados = pd.read_csv("/content/dados.csv")

In [7]:
# EXECUTE!
# Mostra o cabeçalho (head) ou primeiras linhas do dataset.
dados.head()

   UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

## <font color=green>1.2 Tipos de dados</font>
***

### Variáveis qualitativas ordinais

► Variáveis que podem ser ordenadas ou hierarquizardas

In [8]:
# EXECUTE!
sorted(dados['Anos de Estudo'].unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17)]

### Variáveis qualitativas nominais

► Variáveis que não podem ser ordenadas ou hierarquizardas

In [9]:
# EXECUTE!
sorted(dados['UF'].unique())

[np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(35),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(50),
 np.int64(51),
 np.int64(52),
 np.int64(53)]

In [10]:
# EXECUTE!
sorted(dados['Sexo'].unique())

[np.int64(0), np.int64(1)]

In [11]:
# EXECUTE!
sorted(dados['Cor'].unique())

[np.int64(0), np.int64(2), np.int64(4), np.int64(6), np.int64(8)]

### Variáveis quantitativas discretas

► Variáveis que representam uma contagem onde os valores possíveis formam um conjunto finito ou enumerável.

In [12]:
# EXECUTE!
print('Idade de %s até %s anos' % (dados.Idade.min(), dados.Idade.max()))

Idade de 13 até 99 anos

#### <font color='red'>Observação</font>
***
> A variável idade pode ser classificada de três formas distintas:
> 1. <b>QUANTITATIVA DISCRETA</b> - quando representa anos completos (números inteiros);
> 2. <b>QUANTITATIVA CONTÍNUA</b> - quando representa a idade exata, sendo representado por frações de anos; e
> 3. <b>QUALITATIVA ORDINAL</b> - quando representa faixas de idade.

### Variáveis quantitativas contínuas

► Variáveis que representam uma contagem ou mensuração que assumem valores em uma escala contínua (números reais).

In [13]:
# EXECUTE!
print('Altura de %s até %s metros' % (dados['Altura'].min(), dados.Altura.max()))

Altura de 1.339244614 até 2.028496765 metros

### Classificação de uma variável
<img src='https://caelum-online-public.s3.amazonaws.com/1177-estatistica-parte1/01/img001.png' width='70%'>

## 🆗 A PARTE 1 TERMINA AQUI! 🙂
Para continuar a sua prática na parte 2, complete os códigos onde há **??** para depois executar as células com ▶.

# <font color=green>2 DISTRIBUIÇÃO DE FREQUÊNCIAS</font>
***

O primeiro passo em um trabalho de análise é o conhecimento do comportamento das variáveis envolvidas no estudo. Utilizando técnicas estatísticas como as análises das <b>DISTRIBUIÇÕES DE FREQUÊNCIAS</b> e <b>HISTOGRAMAS</b> podemos avaliar melhor a forma como os fenômenos em estudo se distribuem.

## <font color=green>2.1 Distribuição de frequências para variáveis qualitativas</font>
***

### Método 1 - `.value_counts()`  



Leia a respeito aqui: https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.Series.value_counts.html

In [14]:
# 1a contagem - chama a variável 'Sexo' e conta seus dados com o método .value_counts()
dados['Sexo'].value_counts()

Sexo
0    53250
1    23590
Name: count, dtype: int64

In [15]:
# 2a contagem - da mesma variável em percentual com método .value_counts(),que recebe normalize = True como parâmetro
dados['Sexo'].value_counts(normalize=True) * 100     # Normaliza os dados e os coloca na base 1

Sexo
0    69.299844
1    30.700156
Name: proportion, dtype: float64

In [16]:
# Armazena a 1a. contagem na variavel 'frequencia' para melhorar a apresentação dos dados
frequencia = dados['Sexo'].value_counts()    # transformada em uma série do Pandas

In [17]:
# Armazena a 2a. contagem em % na variável 'percentual'
percentual = dados['Sexo'].value_counts(normalize=True) * 100    # transformada em uma série do Pandas

In [18]:
# EXECUTE!
# Para melhorar a apresentação, coloca-se tudo  dentro de novo DataFrame.
# Define-se um dataframe representado pela Tabela de Frequências a ser mostrada.

dist_freq_qualitativas = pd.DataFrame({'Frequência': frequencia, 'Porcentagem (%)': percentual})

In [19]:
# EXECUTE!
# Visualiza o novo dataframe (tabela)
dist_freq_qualitativas

      Frequência  Porcentagem (%)
Sexo
0          53250        69.299844
1          23590        30.700156

In [20]:
# Atribui labels ou as etiquetas Masculino e Feminino aos índices 0 e 1 da tabela usando .rename()
dist_freq_qualitativas.rename(index = {0: 'Masculino', 1: 'Feminino'}, inplace = True)

Observação: O uso de `inplace = True` é necessário para sobrescrever e salvar as mudanças no arquivo.

In [21]:
# Adiciona o título 'Sexo' à coluna dos labels usando .rename_axis()
dist_freq_qualitativas.rename_axis('Sexo', axis = 'columns', inplace = True)

In [22]:
# EXECUTE!
# Visualiza a Tabela de Frequências editada
dist_freq_qualitativas

Sexo       Frequência  Porcentagem (%)
Sexo
Masculino       53250        69.299844
Feminino        23590        30.700156

### Método 2 - `.crosstab()`

O método `.crosstab()` do Pandas faz o cruzamento entre variáveis.  

https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.crosstab.html

In [23]:
# EXECUTE!
# Cria dicionário que transforma dado numérico em string, baseado em variáveis do database.
sexo = {0: 'Masculino',
        1: 'Feminino'}

cor = {0: 'Indígena',
        2: 'Branca',
        4: 'Preta',
        6: 'Amarela',
        8: 'Parda',
        9: 'Sem declaração'}

In [24]:
# Constroi tabela de distribuição de frequências, onde a variavel 'frequencia' é igual a pd.crosstab()
# incluindo as variáveis 'Sexo' nas linhas e 'Cor' nas colunas dessa tabela.

frequencia = pd.crosstab(dados.Sexo, dados.Cor)
# Mostra a tabela de distribuição de frequências
frequencia

Cor     0      2     4    6      8
Sexo
0     256  22194  5502  235  25063
1     101   9621  2889  117  10862

OBSERVAÇÃO: Os valores da tabela correspondem ao cruzamento das variáveis em questão.

In [25]:
# Renomeia a tabela de frequencia com .rename() recebendo 'sexo' como parâmetro de index nas linhas do dicionário.
frequencia.rename(index = sexo, inplace = True) # Usa-se 'inplace = True' para salvar a alteração do dataframe
# Mostra a tabela com as linhas renomeadas
frequencia

Cor          0      2     4    6      8
Sexo
Masculino  256  22194  5502  235  25063
Feminino   101   9621  2889  117  10862

In [26]:
# Renomeia a tabela de frequencia com .rename() recebendo 'cor' como parâmetro de columns no dicionário.
frequencia.rename(columns = cor, inplace = True) # Usa-se inplace = True para salvar a alteração do dataframe
# Mostra a tabela com as colunas renomeadas
frequencia

Cor        Indígena  Branca  Preta  Amarela  Parda
Sexo
Masculino       256   22194   5502      235  25063
Feminino        101    9621   2889      117  10862

In [27]:
# Cria a tabela de percentuais da distribuição de frequência.
# Substitui a variavel frequencia por percentual.
# Dentro do .crosstab(), escreveremos 'normalize = True' para normalizar os valores e multiplicar por 100.
percentual = pd.crosstab(dados.Sexo, dados.Cor, normalize = True) * 100
# Renomeia as linhas e colunas do dataframe
percentual.rename(index = sexo, inplace = True)
percentual.rename(columns = cor, inplace = True)
# Mostra a tabela de percentuais criada
percentual

Cor        Indígena     Branca     Preta   Amarela      Parda
Sexo
Masculino  0.333160  28.883394  7.160333  0.305830  32.617126
Feminino   0.131442  12.520822  3.759761  0.152264  14.135867

In [28]:
# Cria tabela com a média da variável Renda (como parâmetro de values), usando a função agregadora aggfunc = 'mean'
percentual = pd.crosstab(dados.Sexo,
                         dados.Cor,
                         aggfunc = 'mean',
                         values = dados.Renda)
# Renomeia linhas e colunas do dataframe
percentual.rename(index = sexo, inplace = True)
percentual.rename(columns = cor, inplace = True)
# Mostra a tabela de renda media dentro do cruzamento das variáveis Sexo e Cor
percentual

Cor           Indígena       Branca        Preta      Amarela        Parda
Sexo
Masculino  1081.710938  2925.744435  1603.861687  4758.251064  1659.577425
Feminino   2464.386139  2109.866750  1134.596400  3027.341880  1176.758516

## 👇 CONTINUE A PRÁTICA DE 02/06 ATÉ FINALIZAR A PARTE 2 DESTE NOTEBOOK.

## <font color=green>2.2 Distribuição de frequências para variáveis quantitativas (classes personalizadas)</font>
***

### Passo 1 - Especificar os limites de cada classe

Utilizar a seguinte classificação:

<b>A</b> ► Acima de 20 SM

<b>B</b> ► De 10 a 20 SM

<b>C</b> ► De 4 a 10 SM

<b>D</b> ► De 2 a 4 SM

<b>E</b> ► Até 2 SM

Onde <b>SM</b> é o valor do salário mínimo na época. Em nosso caso <b>R$ 788,00</b> (2015):

<b>A</b> ► Acima de 15.760

<b>B</b> ► De 7.880 a 15.760

<b>C</b> ► De 3.152 a 7.880

<b>D</b> ► De 1.576 a 3.152

<b>E</b> ► Até 1.576

In [29]:
# Descobre valores mínimos e máximos da variável Renda (em R$) para construir a distribuição
# Mostra valor mínimo
dados.Renda.min()

0

In [30]:
# Mostra valor máximo
dados.Renda.max()

200000

OBSERVAÇÃO: caso os valores sejam iguais, prosseguir a análise e rever mais adiante.

In [31]:
# Cria lista com limites de renda extraídos das classes E, D, C, B e A, inclui valores mínimo e máximo
classes = [0, 1576, 3152, 7880, 15760, 200000]

In [32]:
# Variável 'labels' recebe lista com etiquetas das classes sociais em ordem crescente
labels = ['E', 'D', 'C', 'B', 'A']

### Passo 2 - Criar a tabela de frequências

https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.cut.html

In [33]:
# Classifica Renda em faixas com limites e etiquetas definidos, inclui valor mínimo
pd.cut(x = dados.Renda,
       bins = classes,
       labels = labels,
       include_lowest = True)

0        E
1        E
2        E
3        C
4        E
        ..
76835    E
76836    E
76837    E
76838    E
76839    E
Name: Renda, Length: 76840, dtype: category
Categories (5, object): ['E' < 'D' < 'C' < 'B' < 'A']

In [34]:
# Mostra cabeçalho do dataframe Dados (5 linhas iniciais)
dados.head()

   UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

In [35]:
# Conta os registros por faixa de renda usando pd.value_counts() com pd.cut()
pd.value_counts(pd.cut(x = dados.Renda,
                       bins = classes,
                       labels = labels,
                       include_lowest = True))

/tmp/ipykernel_504/1421632510.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pd.cut(x = dados.Renda,

Renda
E    49755
D    16700
C     7599
B     2178
A      608
Name: count, dtype: int64

In [36]:
# Armazena a contagem por classe de renda na variável 'frequencia' e exibe o resultado

frequencia = pd.value_counts(
    pd.cut(x = dados.Renda,
               bins = classes,
               labels = labels,
               include_lowest = True)
)
frequencia

/tmp/ipykernel_504/3890186076.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencia = pd.value_counts(

Renda
E    49755
D    16700
C     7599
B     2178
A      608
Name: count, dtype: int64

In [37]:
# Gera a distribuição percentual das classes de renda com 'normalize=True'
percentual = pd.value_counts(
    pd.cut(x = dados.Renda,
               bins = classes,
               labels = labels,
               include_lowest = True),
    normalize = True
)
percentual

/tmp/ipykernel_504/1554271966.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  percentual = pd.value_counts(

Renda
E    0.647514
D    0.217335
C    0.098894
B    0.028345
A    0.007913
Name: proportion, dtype: float64

In [38]:
# Monta tabela com contagem e porcentagem das faixas de renda
dist_freq_quantitativas_personalizadas = pd.DataFrame(
    {'Frequência': frequencia, 'Porcentagem (%)': percentual}
)
dist_freq_quantitativas_personalizadas

       Frequência  Porcentagem (%)
Renda
E           49755         0.647514
D           16700         0.217335
C            7599         0.098894
B            2178         0.028345
A             608         0.007913

In [39]:
# Reorganiza o índice em ordem decrescente para exibir da classe A até E
dist_freq_quantitativas_personalizadas.sort_index(ascending = False)

       Frequência  Porcentagem (%)
Renda
A             608         0.007913
B            2178         0.028345
C            7599         0.098894
D           16700         0.217335
E           49755         0.647514

<p align=justify>OBSERVAÇÃO: Ao analisar os dados, é possível perceber a grande desigualdade social e a precária distribuição de renda, demonstradas através da pesquisa, pois a maioria das pessoas pertence à classe "E" com rendimento menor e pobreza maior, já as maiores rendas se concentram em porcentagem muito pequena de domicílios, correspondentes à classe "A".</p>

## <font color=green>2.3 Distribuição de frequências para variáveis quantitativas (classes de amplitude fixa)</font>
***

### Importando bibliotecas

http://www.numpy.org/

In [40]:
# Importa biblioteca NumPy
import numpy as np

### Passo 1 - Definindo o número de classes

#### Regra de Sturges

# $$k = 1 + \frac {10}{3}\log_{10}n$$

<p align=justify> A <b>Regra de Sturges</b> ajuda a definir a quantidade ideal de classes em uma distribuição de frequências, com base apenas no número de observações da variável, conforme a fórmula acima. </br>
Para aplicá-la, usamos a função  da biblioteca <b>NumPy</b>, importada como <b><i>np</i></b>. Depois, obtemos o número de observações (n) com <b><i>dados.shape[0]</i></b> e executamos a célula para visualizar o valor.</p>

In [41]:
# Mostra número de registros (linhas) e a quantidade de variáveis (colunas) do dataframe
n = dados.shape
print("O numero de registros (linhas) do dataframe é: %s" % n[0])
print("O numero de variáveis (colunas) do dataframe é: %s" % n[1])

O numero de registros (linhas) do dataframe é: 76840
O numero de variáveis (colunas) do dataframe é: 7

In [42]:
# Obtém apenas o número de observações (linhas) do dataset
n = dados.shape[0]
print("O número de observações do dataset é: %s" % n)

O número de observações do dataset é: 76840

In [43]:
# Aplica a Regra de Sturges para calcular o número ideal de classes
k = 1 + (10 / 3) * np.log10(n)
print(k)

17.285291187298853

In [44]:
# Arredonda o valor de k para inteiro conforme a Regra de Sturges
k = int(k.round(0))
k

17

### Passo 2 - Criar a tabela de frequências

In [45]:
# Gera a distribuição da renda em 17 intervalos iguais, inclui valor mínimo
pd.value_counts(
    pd.cut(
        x = dados.Renda,
        bins = 17,
        include_lowest = True
    )
)

/tmp/ipykernel_504/35535026.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(

Renda
(-200.001, 11764.706]       75594
(11764.706, 23529.412]       1022
(23529.412, 35294.118]        169
(35294.118, 47058.824]         19
(47058.824, 58823.529]         16
(94117.647, 105882.353]         6
(58823.529, 70588.235]          5
(70588.235, 82352.941]          4
(188235.294, 200000.0]          3
(82352.941, 94117.647]          1
(117647.059, 129411.765]        1
(129411.765, 141176.471]        0
(105882.353, 117647.059]        0
(141176.471, 152941.176]        0
(152941.176, 164705.882]        0
(164705.882, 176470.588]        0
(176470.588, 188235.294]        0
Name: count, dtype: int64

In [46]:
# Mostra a distribuição das classes mantendo a ordem original dos intervalos
pd.value_counts(
    pd.cut(
        x = dados.Renda,
        bins = 17,
        include_lowest = True
    ),
    sort = False
)

/tmp/ipykernel_504/3887207038.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(

Renda
(-200.001, 11764.706]       75594
(11764.706, 23529.412]       1022
(23529.412, 35294.118]        169
(35294.118, 47058.824]         19
(47058.824, 58823.529]         16
(58823.529, 70588.235]          5
(70588.235, 82352.941]          4
(82352.941, 94117.647]          1
(94117.647, 105882.353]         6
(105882.353, 117647.059]        0
(117647.059, 129411.765]        1
(129411.765, 141176.471]        0
(141176.471, 152941.176]        0
(152941.176, 164705.882]        0
(164705.882, 176470.588]        0
(176470.588, 188235.294]        0
(188235.294, 200000.0]          3
Name: count, dtype: int64

In [47]:
# Salva a contagem das 17 faixas de renda na variável frequencia, mantendo a ordem original
frequencia = pd.value_counts(
    pd.cut(
        x = dados.Renda,
        bins = 17,
        include_lowest = True
    ),
    sort = False
)

/tmp/ipykernel_504/3125739755.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencia = pd.value_counts(

In [48]:
# Calcula o percentual de registros por faixa de renda com 17 classes, mantendo a ordem original
percentual = pd.value_counts(
    pd.cut(
        x = dados.Renda,
        bins = 17,
        include_lowest = True
    ),
    sort = False,
    normalize = True
)
percentual

/tmp/ipykernel_504/1455217640.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  percentual = pd.value_counts(

Renda
(-200.001, 11764.706]       0.983784
(11764.706, 23529.412]      0.013300
(23529.412, 35294.118]      0.002199
(35294.118, 47058.824]      0.000247
(47058.824, 58823.529]      0.000208
(58823.529, 70588.235]      0.000065
(70588.235, 82352.941]      0.000052
(82352.941, 94117.647]      0.000013
(94117.647, 105882.353]     0.000078
(105882.353, 117647.059]    0.000000
(117647.059, 129411.765]    0.000013
(129411.765, 141176.471]    0.000000
(141176.471, 152941.176]    0.000000
(152941.176, 164705.882]    0.000000
(164705.882, 176470.588]    0.000000
(176470.588, 188235.294]    0.000000
(188235.294, 200000.0]      0.000039
Name: proportion, dtype: float64

In [49]:
# Monta DataFrame com a distribuição de renda em 17 faixas iguais
dist_freq_quantitativas_amplitude_fixa = pd.DataFrame(
    {'Frequência': frequencia, 'Porcentagem (%)': percentual}
)
dist_freq_quantitativas_amplitude_fixa

                          Frequência  Porcentagem (%)
Renda
(-200.001, 11764.706]          75594         0.983784
(11764.706, 23529.412]          1022         0.013300
(23529.412, 35294.118]           169         0.002199
(35294.118, 47058.824]            19         0.000247
(47058.824, 58823.529]            16         0.000208
(58823.529, 70588.235]             5         0.000065
(70588.235, 82352.941]             4         0.000052
(82352.941, 94117.647]             1         0.000013
(94117.647, 105882.353]            6         0.000078
(105882.353, 117647.059]           0         0.000000
(117647.059, 129411.765]           1         0.000013
(129411.765, 141176.471]           0         0.000000
(141176.471, 152941.176]           0         0.000000
(152941.176, 164705.882]           0         0.000000
(164705.882, 176470.588]           0         0.000000
(176470.588, 188235.294]           0         0.000000
(188235.294, 200000.0]             3         0.000039

In [50]:
# Define os limites das faixas da variável Altura
classes = [dados.Altura.min(), 1.65, 1.75, dados.Altura.max()]

# Define os rótulos para cada faixa
labels = ['1 - Baixa', '2 - Média', '3 - Alta']

# Calcula a frequência de cada faixa de Altura
frequencia = pd.value_counts(
    pd.cut(
        x = dados.Altura
        bins = classes,
        labels = labels,
        include_lowest = True
    )
)

# Calcula o percentual de cada faixa de Altura
percentual = pd.value_counts(
    pd.cut(
        x = dados.Altura,
        bins = classes,
        labels = labels,
        include_lowest = True
    ), normalize = True
) * 100

# Cria o DataFrame com frequência e percentual
dist_freq_altura = pd.DataFrame(
    {'Frequência': frequencia, 'Porcentagem (%)': percentual}
)

# Renomeia o eixo das colunas para 'Estaturas'
dist_freq_altura.rename_axis('Estaturas', axis= 'columns', inplace = True)

# Ordena os rótulos em ordem crescente
dist_freq_altura.sort_index(ascending = True, inplace = True)

# Exibe o resultado final
dist_freq_altura

SyntaxError: invalid syntax. Perhaps you forgot a comma? (617541501.py, line 10)

## <font color=green>2.4 Histograma</font>
***
<b>HISTOGRAMA</b> é a representação gráfica de uma distribuição de frequências. É uma gráfico formado por um conjunto de retângulos colocados lado a lado, onde a área de cada retângulo é proporcional à frequência da classe que ele representa.

### Importando a biblioteca

https://seaborn.pydata.org/

In [ ]:
# Importa biblioteca Seaborn para visualizar dados estatísticos e baseada em matplotlib().
import seaborn as sns

In [ ]:
# Gera o histograma de Altura com Seaborn
# uso de 'ax' é padrão na documentação do Seaborn e Matplotlib, facilita a manipulação do gráfico depois
ax = sns.histplot(dados.Altura, kde = False)

# Configura a visualiação do gráfico histograma
ax.figure.set_size_inches(12, 6)
ax.set_title('Distribuição de Frequências - Altura', fontsize=18)
ax.set_xlabel('Metros', fontsize=14)
ax # representa o objeto gráfico

<p align=justify> OBSERVAÇÃO: O histograma é composto por barras unidas, cuja área é proporcional à frequência da classe, possui seu pico por volta do valor "17" do eixo X.</p>

In [ ]:
# Cria histograma com curva de densidade (KDE) e personaliza título, tamanho e rótulo do eixo X
# Cria histograma com curva de densidade (KDE) usando histplot
ax = sns.histplot(dados.Altura, kde=True)

# Personaliza o gráfico
ax.figure.set_size_inches(12, 6)
ax.set_title('Distribuição de Frequências - Altura - KDE', fontsize=18)
ax.set_xlabel('Metros', fontsize=14)
ax

In [ ]:
# Gera histograma simples da Altura com 50 barras (bins) usando apenas Pandas
dados.Altura.hist(bins = 50, figsize=(12,6))

In [ ]:
# Mostra a distribuição de classes personalizadas antes da visualização gráfica
dist_freq_quantitativas_personalizadas

In [ ]:
# Gera gráfico de barras com base na tabela de frequências personalizadas
# O gráfico tem largura, cor e transparência ajustadas para simular um histograma
dist_freq_quantitativas_personalizadas['Frequência'].plot.bar(
    width=1,                # barras unidas, simulando histograma
    color='blue',           # cor azul
    alpha=0.2,              # transparência leve
    figsize=(12, 6)         # tamanho do gráfico
)

## 🆗**A PRÁTICA DE 02/06/26 TERMINA AQUI.** 😃

Salve o seu progresso e NÃO EXECUTE MAIS NENHUMA CÉLULA a partir daqui.

# <font color=green>3 MEDIDAS DE TENDÊNCIA CENTRAL</font>
***

## DataFrame de exemplo

## <font color=green>3.1 Média aritmética</font>
***

É representada por $\mu$ quando se refere à população e por $\bar{X}$ quando se refere à amostra

# $$\mu = \frac 1n\sum_{i=1}^{n}X_i$$

onde

$n$ = número de observações (registros)

$X_i$ = valor da i-ésima observação (registro)

## <font color=green>3.2 Mediana</font>
***

Para obtermos a mediana de uma conjunto de dados devemos proceder da seguinte maneira:
1. Ordenar o conjunto de dados;
2. Identificar o número de observações (registros) do conjunto de dados ($n$);
3. Identicar o elemento mediano:

> Quando $n$ for ímpar, a posição do elemento mediano será obtida da seguinte forma:


# $$Elemento_{Md} = \frac{n+1}2$$

> Quando $n$ for par, a posição do elemento mediano será obtida da seguinte forma:


# $$Elemento_{Md} = \frac{n}2$$

4. Obter a mediana:

> Quando $n$ for ímpar:


# $$Md = X_{Elemento_{Md}}$$

> Quando $n$ for par:


# $$Md = \frac{X_{Elemento_{Md}} + X_{Elemento_{Md}+1}}2$$
***

### Exemplo 1 - n ímpar

<img src='https://caelum-online-public.s3.amazonaws.com/1177-estatistica-parte1/01/img002.png' width='40%' style="float:left">

### Exemplo 2 - n par

<img src='https://caelum-online-public.s3.amazonaws.com/1177-estatistica-parte1/01/img003.png' width='50%' style="float:left">

### Obtendo a mediana em nosso dataset

## <font color=green>3.3 Moda</font>
***

Pode-se definir a moda como sendo o valor mais frequente de um conjunto de dados. A moda é bastante utilizada para dados qualitativos.

### Obtendo a moda em nosso dataset

## <font color=green>3.4 Relação entre média, mediana e moda</font>
***

<img src='https://caelum-online-public.s3.amazonaws.com/1177-estatistica-parte1/01/img004.png' width='80%'>

### Avaliando a variável RENDA

***

### Avaliando a variável ALTURA

***

### Avaliando a variável ANOS DE ESTUDO

# <font color=green>4 MEDIDAS SEPARATRIZES</font>
***

## <font color=green>4.1 Quartis, decis e percentis</font>
***

Há uma série de medidas de posição semelhantes na sua concepção à mediana, embora não sejam medidas de tendência central. Como se sabe, a mediana divide a distribuição em duas partes iguais quanto ao número de elementos de cada parte. Já os quartis permitem dividir a distribuição em quatro partes iguais quanto ao número de elementos de cada uma; os decis em dez partes e os centis em cem partes iguais.

## <font color=green>4.2 Box-plot</font>
***

O box plot dá uma idéia da posição, dispersão, assimetria, caudas e dados discrepantes (outliers). A posição central é dada pela mediana e a dispersão por $IIQ$. As posições relativas de $Q1$, $Mediana$ e $Q3$ dão uma noção da simetria da distribuição. Os comprimentos das cauda são dados pelas linhas que vão do retângulo aos valores remotos e pelos valores atípicos.

<img src='https://caelum-online-public.s3.amazonaws.com/1177-estatistica-parte1/01/img005.png' width='65%'>

<img src='https://caelum-online-public.s3.amazonaws.com/1177-estatistica-parte1/01/img006.png' width='80%'>

# <font color=green>5 MEDIDAS DE DISPERSÃO</font>
***

Embora as medidas de posição forneçam uma sumarização bastante importante dos dados, elas podem não ser suficientes para caracterizar conjuntos distintos, especialmente quando as observações de determinada distribuição apresentarem dados muito dispersos.

## <font color=green>5.1 Desvio médio absoluto</font>
***


# $$DM = \frac 1n\sum_{i=1}^{n}|X_i-\bar{X}|$$

## <font color=green>5.2 Variância</font>
***

### Variância

A variância é construída a partir das diferenças entre cada observação e a média dos dados, ou seja, o desvio em torno da média. No cálculo da variância, os desvios em torno da média são elevados ao quadrado.

### Variância populacional

# $$\sigma^2 = \frac 1n\sum_{i=1}^{n}(X_i-\mu)^2$$

### Variância amostral

# $$S^2 = \frac 1{n-1}\sum_{i=1}^{n}(X_i-\bar{X})^2$$

## <font color=green>5.3 Desvio padrão</font>
***

Uma das restrições da variância é o fato de fornecer medidas em quadrados das unidades originais - a variância de medidas de comprimento, por exemplo, é em unidades de área. Logo, o fato de as unidades serem diferentes dificulta a comparação da dispersão com as variáveis que a definem. Um modo de eliminar essa dificuldade é considerar sua raiz quadrada.

### Desvio padrão populacional

# $$\sigma = \sqrt{\frac 1n\sum_{i=1}^{n}(X_i-\mu)^2} \Longrightarrow \sigma = \sqrt{\sigma^2}$$

### Desvio padrão amostral

# $$S = \sqrt{\frac 1{n-1}\sum_{i=1}^{n}(X_i-\bar{X})^2} \Longrightarrow S = \sqrt{S^2}$$